### ISSUE TITLE
Blog URL ("blog_url") is missing for Change Log entry 9

### ISSUE THREAD

**Issue by mpawlow** [IBMDataScience/datascix#15]
### Problem 

"Read the Blog Post" button link is broken for entry 9: "Admit it. You know you have your favorites!"
See: https://apsportal.ibm.com/whats-new?context=analytics

**Comment by mpawlow** [comment]
FYI @msochka @aruizga7

**Comment by msochka** [comment]
I created a general link to the blogs for the item that did not have a specific entry. At least this way the user is led to the blog entries where they can browse.

**Comment by mpawlow** [comment]
Thanks @msochka
