### ISSUE TITLE
Image resolutions for Change Log entries 9, 10 are visually stretched

### ISSUE THREAD

**Issue by mpawlow** [IBMDataScience/datascix#16]
### Problem

See: https://apsportal.ibm.com/whats-new?context=analytics

![image](https://cloud.githubusercontent.com/assets/7130422/20413435/1024a84c-acfb-11e6-9ab4-5bf7201f3cb2.png)

**Comment by mpawlow** [comment]
FYI: @msochka @aruizga7

**Comment by aruizga7** [comment]
@mpawlow do you need the images in another resolution or how do you want to solve this?

**Comment by mpawlow** [comment]
@aruizga7 
The images in question have a natural width of ~ 220 pixels.
Whereas, the UI is forcing the image dimensions to be exactly: `479 x 223` pixels.
This is far too strict in my opinion.

I need to check with a designer to determine whether they want to strictly manage the height as well as the width (i.e. usually the height is variable).

The simple tactical solution (for now) would be to scale the image up to exactly `479 x 223` pixels or more appropriately just increasing the background canvas width (a designer could do this for us in 5 mins).

The long term solution is to set image guidelines.
I suggest just setting a min width of 400 px and allowing the height to be variable.

**Comment by msochka** [comment]
I re-captured the images to make them full screen and comparable in size to the others in the series. They are proportionally 479 x 223, but the images are larger. I assume that will be OK. I updated all instances of the files. Please verify and test my work. I don't know how to send these items into production. @mpawlow @aruizga7 

You can re-open this item if there are any problems. Thanks!
