### ISSUE TITLE
Add support in Change Log JSON schema for specifying a blog post author image

### ISSUE THREAD

**Issue by mpawlow** [IBMDataScience/datascix#18]
Proposed Field:  `author_image_url`

**Comment by msochka** [comment]
@mpawlow Hey, Mike, I have a related item to this work. @aruizga7 would like to make the avatar (blogger photo) smaller, in addition to having the photo as part of the JSON file. There will be more bloggers in the mix in the future for sure!

**Comment by mpawlow** [comment]
@msochka Working on it.
Tracked by an epic in the IBM GitHub Enterprise repository.

**Comment by mpawlow** [comment]
Done.

FYI: @msochka @aruizga7 
DSX will now read and use the image URL specified in the new `author_image_url` field in the JSON file.
All we need now is to upload polished images of Change Log entry authors from the Content and OM teams.
