### ISSUE TITLE
What's New: Create entry for Data Refinery

### ISSUE THREAD

**Issue by msochka** [IBMDataScience/datascix#37]
Here's the original blog post on Medium:

https://medium.com/ibm-data-science-experience/self-service-data-preparation-with-ibm-data-refinery-5166d581014e

You will need to get the author's photo and add it to the What's New repo. 

Here's the title and text of the What's New post:

**Like finery for your data!**

Dahling, you look mahvelous! And with IBM Data Refinery you'll have your data looking better that ever. This self-service data preparation tool lets you cleanse, shape, and prepare data without the need for IT involvement. Because you can use Data Refinery to both transform and visualize data in the same interface, you can better understand your distribution of values taking you from frump to fashionista with data that'll be the envy of everyone!

**Comment by wswtizer** [comment]
@ktsuench Here is a new one. Check with Mike P to see if the audience tags are working. This is a Data Refinery one. Thanks.

**Comment by msochka** [comment]
Note from another conversation:

Well from the code side, only the standard entitlement strings are supported:

```
const VALID_AUDIENCES = [
	"data_science_experience",
	"data_catalog",
	"data_refinery"
];
```

If the file contains any other strings for audience an error will be thrown.
I will handle displaying these values properly once they're fetched.
I'll also be updating the readme in the datascix repo to explain this new field.

**Comment by ktsuench** [comment]
I'll add back in the audience part of the entry for QA and PROD once the tags are working.
