### ISSUE TITLE
What's New: Create entry for Data Catalog

### ISSUE THREAD

**Issue by msochka** [IBMDataScience/datascix#38]
Original blog post on Medium is here: https://medium.com/ibm-data-science-experience/discover-catalog-and-govern-data-with-ibm-data-catalog-5e1ef7d28df2

You will need to add the author photo to the repo. (New author)

Here's the title and text to use:

**Drowning in your data lake? IBM Data Catalog to the rescue!**

IBM Data Catalog is a lifeline for data scientists, data analysts ... actually make that ANYONE who works with data! Regardless of where data resources reside, you can find them with pinpoint accuracy. Use IBM Data Catalog to govern, catalog, automatically classify, refine, and analyze your data. You can even monitor policies and create a business glossary so that you entire team is synchronized. So get your tech suit on and head for open waters, today's the day you conquer your data lake!

**Comment by wswtizer** [comment]
@ktsuench Here is another one... This one is audience Data Catalog.... not sure the exact format it needs to be in though. Thanks.

**Comment by msochka** [comment]
Note from another conversation:

Well from the code side, only the standard entitlement strings are supported:

```
const VALID_AUDIENCES = [
	"data_science_experience",
	"data_catalog",
	"data_refinery"
];
```

If the file contains any other strings for audience an error will be thrown.
I will handle displaying these values properly once they're fetched.
I'll also be updating the readme in the datascix repo to explain this new field.

**Comment by ktsuench** [comment]
I'll add back in the audience part of the entry for QA and PROD once the tags are working.

**Comment by nickmazzi** [comment]
Yes I updated the wiki with the audience info.
Also, the code to handle the audience is not available in QA or Prod yet, it will be available there on Wed and Fri respectively. So we cannot merge the audience object to those files until the code to handle it is pushed.
