### ISSUE TITLE
What's New: Data Science Experience Environments

### ISSUE THREAD

**Issue by msochka** [IBMDataScience/datascix#45]
There's a new post. We need to create a new entry in the JSON files.

**Comment by msochka** [comment]
Background information is here: 

https://github.ibm.com/dap/dsx-documentation-source/issues/989#issuecomment-4767306

**Comment by msochka** [comment]
Text approved by @gfilla:

**Science 101: control the environment to control the experiment**

It's like my Chemistry teacher always said, "You can't hope to get the experiment right unless you control the environment." That's just one aspect of Data Science Experience Environments, which is in beta right now for all users to try. This new functionality, which defines a relationship between a tool, software configuration, and hardware configuration, makes it easier than ever to customize, scale, and manage your work. For example, it gives you the power to configure a Jupyter notebook environment configured with Anaconda 5.0 with 4 vCPU and 16 GB RAM. By adding it to a project, like any other asset, you can standardize it for all your collaborators. Gee, Dr. Howard was right all along!

**Comment by msochka** [comment]
@wswtizer Please assign someone to take care of this new What's New post. Thanks. The image will need some work to fit the correct size. Work with @gfilla on that. I think it can either be the existing image with a neutral background or a retake of a larger portion of the UI.

**Comment by msochka** [comment]
![image](https://user-images.githubusercontent.com/22508853/36312937-0fc4a4a0-12fe-11e8-8cd4-f9db640b3436.png)

**Comment by wswtizer** [comment]
@ktsuench - are you able to take this today? @gfilla - what image do you want in the post? Thanks.

**Comment by wswtizer** [comment]
@msochka - Mike, Kent is out of the office today. I don't have anyone who can push this out today. Would you be able to do it? Thanks.

**Comment by wswtizer** [comment]
@msochka - never mind. We will get it looked at. Thanks.

**Comment by ktsuench** [comment]
Updated image for entry

![image](https://user-images.githubusercontent.com/6343135/36321849-423b4360-1319-11e8-8a05-8a47cacd3187.png)

**Comment by ktsuench** [comment]
Done.
