### ISSUE TITLE
Watson Studio What's New for SPSS Modeler

### ISSUE THREAD

**Issue by msochka** [IBMDataScience/datascix#46]
All of the information that you need for this work is contained in the following issue:

https://github.ibm.com/dap/dsx-documentation-source/issues/1192#issuecomment-5140015

Very important. This What's New needs to go LIVE on PROD only when the THINK! go live is authorized. Right now that is Tuesday, March 20, 2018 at 4AM Pacific time. 

It should go live on DEV and QA as soon as possible so it can be reviewed by OMs and CD.

**Comment by msochka** [comment]
Just FYI for @wswtizer and @mpawlow 

In Wendy's absence today, I am assigning this out to Kent.

@ktsuench Feel free to pick a graphic from the blog post. If you have any doubt, please reach out to @gfilla for direction as to which graphic to choose.

Thanks!

**Comment by ktsuench** [comment]
@msochka who do I ask to add @sslyu Simon as a contributor? He'll be taking over these tasks.

**Comment by msochka** [comment]
Sure thing. I would add Simon but don't have Admin privileges. @mpawlow can add him.

Create an issue and assign it to Mike. You might want to ping him as well.

**Comment by ktsuench** [comment]
Okay I added issue #47 and I'll ping him too.

**Comment by ktsuench** [comment]
@msochka what audience is this for?

**Comment by sslyu** [comment]
@msochka You can check the blog entries on qa and dev

**Comment by msochka** [comment]
Oh, right. I forgot about all that. This is all for CLOUD and Watson Studio / DSX

Does that answer the question?

**Comment by msochka** [comment]
Look good!

**Comment by ktsuench** [comment]
Available on PROD.

**Comment by msochka** [comment]
Outstanding. Thanks so much!
