### ISSUE TITLE
Watson Studio What's New post for Deep Learning

### ISSUE THREAD

**Issue by msochka** [IBMDataScience/datascix#48]
The main information for this post is here: https://github.ibm.com/dap/dsx-documentation-source/issues/1194#issuecomment-5142452

The posts to QA and DEV need to be made immediately.

The post on PROD needs to be timed with the THINK! go live, which is currently scheduled for Tuesday, March 20th at 4AM Pacific Time.

**Comment by msochka** [comment]
@ktsuench Just giving you an FYI

@sslyu Thanks for doing this time critical work!

**Comment by sslyu** [comment]
@msochka Hi Mike, Anthony Stevens doesn't have an image (besides the lego dude on github and a robot on medium) that we can use. Please let me know if the lego or robot is acceptable

**Comment by msochka** [comment]
That's hilarious. So tempting ....  :-) I will ping him.

**Comment by msochka** [comment]
![author_image_anthony_stevens](https://user-images.githubusercontent.com/22508853/37617530-c961a054-2b89-11e8-8cef-1e1251ae3b7a.jpeg)

I think we should use this. Let's go forward with it and if we need to change, I will upload a file with the identical name. At least this approach enables us to keep this moving along for now.

**Comment by sslyu** [comment]
@msochka Did you mean THINK! go live is on March 20, not May 20? Also, will the posts to QA and DEV be published March 20 as well?

**Comment by msochka** [comment]
THINK! Go live on March 20th. Tomorrow. Sorry. Very little sleep these past few weeks.

QA and DEV can be published now, so that we can review. Then, wait for tomorrow to push the PROD versions out.

Today there will be a total of FOUR (4) What's New posts. Two are done and two are waiting for final approval by OM. I will create issues here for the remaining two and assign them to you. Let me know if you have any questions or concerns. So far so good!

**Comment by sslyu** [comment]
@msochka Mike the posts are live on QA and DEV.

**Comment by ktsuench** [comment]
Available on PROD.

**Comment by msochka** [comment]
Cool beans!
