### ISSUE TITLE
Watson Studio What's New for Watson Studio main blog post

### ISSUE THREAD

**Issue by msochka** [IBMDataScience/datascix#49]
The following issue contains relevant information:
https://github.ibm.com/dap/dsx-documentation-source/issues/1191#issuecomment-5144832

The blog post URL is here:
https://medium.com/ibm-watson/introducing-ibm-watson-studio-e93638f0bb47

**Comment by msochka** [comment]
The finalized text:

**Hello, my name is Watson. Welcome to my Studio.**

IBM Watson Studio makes AI more accessible across teams with tools for data scientists, application developers and subject matter experts. With a choice of machine learning and deep learning frameworks and visual or coding interfaces, Watson Studio takes the pain out of building, training, and deploying models. The new Watson Studio Dashboard makes it easy to explore and share data visualizations. And you were wondering what Watson was up to since winning Jeopardy!

**Comment by ktsuench** [comment]
This is available for review on DEV and QA.

**Comment by ktsuench** [comment]
Available on PROD.

**Comment by msochka** [comment]
Great work! Thanks so much for your dedication and effort!
