### ISSUE TITLE
Watson Studio What's New for Data Refinery

### ISSUE THREAD

**Issue by msochka** [IBMDataScience/datascix#50]
This is the final What's New for THINK!

The issue can be found here:
https://github.ibm.com/dap/dsx-documentation-source/issues/1193

I don't have final approval on the language, but I would like to see us at least get started on the JSON file work, if that's possible.

**Comment by msochka** [comment]
I am pestering the OM for her approval. Hopefully it comes through in the next half hour. If either or both of you need to leave, please let me know. We can arrange a hand-off. 

I appreciate your help.

Early tomorrow morning, the PROD versions will need to be updated/go live. I think that makes it 7AM our time. Is that something that you can manage?

**Comment by ktsuench** [comment]
@msochka I'll try and handle it and have them pushed out in production in the morning.

**Comment by msochka** [comment]
Still tinkering ....

**Comment by ktsuench** [comment]
This is available on DEV and QA now.

**Comment by msochka** [comment]
Thanks. I say that that looks good. If I don't hear back from anyone it's what they will have in place in the morning. We can always update it tomorrow afternoon. I am not able to stay up all night for this one item. 

I appreciate your flexibility, Kent. If you are good to push those in the morning, that'd be great.

I will take a look when I get online.

**Comment by msochka** [comment]
Just confirming that this was approved AS YOU HAVE it up on DEV/QA. Whew!

Let's just push all four out to Prod tomorrow morning at 7AM Eastern Time and we're good. I will leave that in your hands. I can check and then I will close all 4 issues.

Great work, @ktsuench and @sslyu I appreciate it the quick turnaround!

**Comment by ktsuench** [comment]
Available on PROD.

**Comment by msochka** [comment]
Great work! Thanks. We're live!
